[package]
name = "oynx"
version = "0.1.2"
edition = "2024"

[dependencies]
anyhow = "1"
dirs = "7"
eframe = { version = "0.36", features = ["persistence"] }
egui = "0.36"
env_logger = "0.11"
image = { version = "0.25", default-features = false, features = ["jpeg", "png"] }
librespot = { version = "0.8", default-features = false, features = ["native-tls", "rodio-backend", "with-libmdns"] }
log = "0.4"
reqwest = { version = "0.12", default-features = false, features = ["blocking", "json", "native-tls"] }
rustfft = "6"
serde = { version = "1", features = ["derive"] }
serde_json = "1"
sha2 = "0.10"
tokio = { version = "1", features = ["rt-multi-thread", "macros", "sync", "time"] }
tray-icon = "0.25"
